apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-cd-final-project-pipeline
spec:
  params:
    - name: repoUrl
      type: string
    - name: revision
      type: string
      default: main
    - name: namespace
      type: string
    - name: app
      type: string
      default: ci-cd-final-project
    - name: image
      type: string
    - name: port
      type: string
      default: "8000"

  workspaces:
    - name: shared-workspace

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: git-clone
      runAfter: ["cleanup"]
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repoUrl)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: flake8
      runAfter: ["git-clone"]
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: nose
      runAfter: ["flake8"]
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: buildah
      runAfter: ["nose"]
      taskRef:
        name: buildah
      params:
        - name: image
          value: $(params.image)
        - name: tlsVerify
          value: "false"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy
      runAfter: ["buildah"]
      taskRef:
        name: openshift-client
      params:
        - name: namespace
          value: $(params.namespace)
        - name: app
          value: $(params.app)
        - name: image
          value: $(params.image)
        - name: port
          value: $(params.port)
      workspaces:
        - name: source
          workspace: shared-workspace