---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
      description: Workspace shared by all tasks
  steps:
    - name: cleanup
      image: alpine:3.19
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Cleaning workspace..."
        rm -rf ./* ./.??* || true
        echo "Done."

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: repoUrl
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git:2.45.2
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo "Cloning $(params.repoUrl) @ $(params.revision)"
        rm -rf repo
        git clone $(params.repoUrl) repo
        cd repo
        git checkout $(params.revision)
        echo "Repo ready at $(workspaces.output.path)/repo"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)/repo
      script: |
        #!/bin/sh
        set -e
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        echo "Running flake8..."
        flake8 service --count --statistics

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)/repo
      script: |
        #!/bin/sh
        set -e
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Running nose tests..."
        nosetests -v

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: image
      type: string
    - name: tlsVerify
      type: string
      default: "false"
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:v1.35.0
      securityContext:
        privileged: true
      workingDir: $(workspaces.source.path)/repo
      script: |
        #!/bin/sh
        set -e
        echo "Building image: $(params.image)"
        buildah bud --tls-verify=$(params.tlsVerify) -t $(params.image) .
        echo "Pushing image: $(params.image)"
        buildah push --tls-verify=$(params.tlsVerify) $(params.image)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
spec:
  params:
    - name: namespace
      type: string
    - name: app
      type: string
    - name: image
      type: string
    - name: port
      type: string
      default: "8000"
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:4.15
      script: |
        #!/bin/sh
        set -e
        echo "Switching to project $(params.namespace)"
        oc project $(params.namespace)

        echo "Deploying app $(params.app) with image $(params.image)"
        if oc get deployment/$(params.app) >/dev/null 2>&1; then
          oc set image deployment/$(params.app) $(params.app)=$(params.image)
        else
          oc new-app --name=$(params.app) $(params.image)
        fi

        echo "Ensuring service exists on port $(params.port)"
        if ! oc get svc/$(params.app) >/dev/null 2>&1; then
          oc expose deployment/$(params.app) --port=$(params.port) --name=$(params.app)
        fi

        echo "Ensuring route exists"
        if ! oc get route/$(params.app) >/dev/null 2>&1; then
          oc expose svc/$(params.app) --name=$(params.app)
        fi

        echo "Waiting for rollout..."
        oc rollout status deployment/$(params.app) --timeout=180s