apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:3.20
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Cleaning workspace..."
        rm -rf ./* ./.??* || true
        echo "Cleanup done."

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
  workspaces:
    - name: source
  steps:
    - name: git-clone
      image: alpine/git:2.45.2
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        git clone $(params.url) .
        git checkout $(params.revision)

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: flake8
spec:
  workspaces:
    - name: source
  steps:
    - name: flake8
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        flake8 . --max-line-length=120

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  steps:
    - name: nose
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        nosetests -v --with-spec --spec-color

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: image
      type: string
    - name: tlsVerify
      type: string
      default: "false"
  workspaces:
    - name: source
  steps:
    - name: buildah
      image: quay.io/buildah/stable:v1.36.0
      securityContext:
        privileged: true
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        buildah bud --tls-verify=$(params.tlsVerify) -t $(params.image) -f Dockerfile .
        buildah push --tls-verify=$(params.tlsVerify) $(params.image) docker://$(params.image)

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: openshift-client
spec:
  params:
    - name: namespace
      type: string
    - name: app
      type: string
    - name: image
      type: string
    - name: port
      type: string
      default: "8000"
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:4.15
      script: |
        #!/bin/sh
        set -e
        oc project $(params.namespace)

        oc apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $(params.app)
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: $(params.app)
          template:
            metadata:
              labels:
                app: $(params.app)
            spec:
              containers:
              - name: $(params.app)
                image: $(params.image)
                env:
                - name: PORT
                  value: "$(params.port)"
                ports:
                - containerPort: $(params.port)
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: $(params.app)
        spec:
          selector:
            app: $(params.app)
          ports:
          - name: http
            port: 80
            targetPort: $(params.port)
        EOF

        oc expose svc/$(params.app) || true
        oc rollout status deployment/$(params.app) -n $(params.namespace) --timeout=180s
        oc get route $(params.app) -n $(params.namespace) -o jsonpath='{.spec.host}{"\n"}'